name: release

on: workflow_dispatch

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - uses: martinbeentjes/npm-get-version-action@master
        id: package-version
      - uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            **[${{ github.actor }}](https://github.com/${{ github.actor }})** vừa biu thành công **${{ github.repository }}** phiên bản **${{ steps.package-version.outputs.current-version}}**
            Kiểm tra tại https://www.npmjs.com/package/@fpt-blockchain/web3js-quorum
