name: release

on:
  release:
    types: [published]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: echo "`jq '.version="${{ github.event.release.tag_name }}"' package.json`" > package.json
      - run: npm ci
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            **[${{ github.actor }}](https://github.com/${{ github.actor }})** vừa biu thành công **${{ github.repository }}** phiên bản **${{ github.event.release.tag_name }}**
            Kiểm tra tại https://www.npmjs.com/package/@fpt-blockchain/web3js-quorum
